import { type NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import { type KitabHadith } from "~/utils/types";

const kitabHadith: KitabHadith[] = [
  {
    name: "Sahih al-Bukhari",
    author: "Imam al-Bukhari",
    authorRealName: "Abu Abdullah Muhammad bin Ismail al-Bukhari",
    url: "/bukhari",
  },
  {
    name: "Sahih Muslim",
    author: "Imam Muslim",
    authorRealName: "Muslim bin al-Hajjaj al-Naysaburi",
    url: "/muslim",
  },
];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hadith App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-900">
        <div className="flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Jami&apos; Al-Kutub Al-Sittah
          </h1>
          <div className="flex flex-col items-center">
            <h1 className="m-4 text-2xl font-semibold text-slate-300/90">
              Pilih Kitab
            </h1>
            <div>
              <ul className="grid grid-cols-1 gap-4 md:grid-cols-2">
                {kitabHadith.map((kitab, idx) => {
                  return (
                    <li
                      key={idx}
                      className="rounded-lg p-4 text-slate-300 ring-1"
                    >
                      <Link href={kitab.url}>{kitab.name}</Link>
                    </li>
                  );
                })}
              </ul>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
