import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";

import { api } from "~/utils/api";

export type Hadith = {
  number: number;
  arab: string;
  id: string;
};

const Home: NextPage = () => {
  const hadithData = api.bukhari.getAll.useQuery();

  const mockHadithData = Array.from({ length: 10 }, (_, i) => {
    return {
      hadithName: `Sahih Bukhari ${i + 1}`,
      hadithNo: i + 1,
    };
  });

  return (
    <>
      <Head>
        <title>Hadith App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Hadith</span> App
          </h1>
          <div>
            {hadithData.isLoading ? (
              <div>Loading...</div>
            ) : (
              <div className="grid grid-cols-2 gap-4 text-white">
                {hadithData.data?.map((hadith: Hadith, idx: number) => {
                  return (
                    <div
                      key={idx}
                      className="mt-4 flex rounded-md border border-slate-500 p-4 rtl:items-start rtl:justify-start"
                    >
                      <h1>No: {hadith.number}</h1>
                      <div className="flex flex-col mt-4">
                        <p className="py-2 text-justify flex items-center">Matan: {hadith.arab}</p>
                        <p className="py-2">Terjemahan: {hadith.id}</p>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
